// Základné testovacie dáta pre Vpick.
// Polia sú zjednodušené tak, aby sa dali mapovať na otázky sprievodcu.

const VpickShoes = [
  // ROAD – DAILY / STABILITA / NEUTRÁL
  {
    id: "asics-novablast-5",
    brand: "ASICS",
    model: "Novablast 5",
    segment: "daily",
    surface: "road",
    gait: "neutral",
    runnerLevel: "intermediate",
    targetDistance: "5-21k",
    cushioning: "high",
    dropCat: "mid", // 6-8
    width: "standard",
    budget: "120-170",
    tech: "FF Blast+ Eco pena, všestranný tréning",
    weight: "~255 g",
    terrainDetail: "cesta / tvrdé povrchy",
    image: "asics-novablast-5.png"
  },
  {
    id: "asics-gt-2000-13",
    brand: "ASICS",
    model: "GT-2000 13",
    segment: "daily-stability",
    surface: "road",
    gait: "support",
    runnerLevel: "intermediate",
    targetDistance: "5-21k",
    cushioning: "medium",
    dropCat: "mid",
    width: "standard+wide",
    budget: "120-170",
    tech: "FF Blast, LITETRUSS stabilita",
    weight: "~270 g",
    terrainDetail: "cesta",
    image: "asics-gt-2000-13.png"
  },
  {
    id: "brooks-ghost-17",
    brand: "Brooks",
    model: "Ghost 17",
    segment: "daily",
    surface: "road",
    gait: "neutral",
    runnerLevel: "beginner",
    targetDistance: "5-21k",
    cushioning: "medium",
    dropCat: "high",
    width: "standard+wide",
    budget: "120-170",
    tech: "DNA Loft v3, mäkký tréning",
    weight: "~280 g",
    terrainDetail: "cesta",
    image: "brooks-ghost-17.png"
  },
  {
    id: "brooks-adrenaline-gts-23",
    brand: "Brooks",
    model: "Adrenaline GTS 23",
    segment: "daily-stability",
    surface: "road",
    gait: "support",
    runnerLevel: "beginner",
    targetDistance: "5-21k",
    cushioning: "medium",
    dropCat: "high",
    width: "standard+wide",
    budget: "120-170",
    tech: "GuideRails stabilita",
    weight: "~295 g",
    terrainDetail: "cesta",
    image: "brooks-adrenaline-gts-23.png"
  },
  {
    id: "hoka-clifton-10",
    brand: "Hoka",
    model: "Clifton 10",
    segment: "daily",
    surface: "road",
    gait: "neutral",
    runnerLevel: "beginner",
    targetDistance: "5-21k",
    cushioning: "high",
    dropCat: "low",
    width: "standard+wide",
    budget: "120-170",
    tech: "CMEVA pena, Meta-Rocker",
    weight: "~250 g",
    terrainDetail: "cesta",
    image: "hoka-clifton-10.png"
  },
  {
    id: "hoka-arahi-7",
    brand: "Hoka",
    model: "Arahi 7",
    segment: "daily-stability",
    surface: "road",
    gait: "support",
    runnerLevel: "intermediate",
    targetDistance: "5-21k",
    cushioning: "medium",
    dropCat: "low",
    width: "standard",
    budget: "120-170",
    tech: "J-Frame stabilita",
    weight: "~270 g",
    terrainDetail: "cesta",
    image: "hoka-arahi-7.png"
  },
  {
    id: "nb-1080v14",
    brand: "New Balance",
    model: "Fresh Foam X 1080 v14",
    segment: "daily",
    surface: "road",
    gait: "neutral",
    runnerLevel: "intermediate",
    targetDistance: "10-42k",
    cushioning: "high",
    dropCat: "low",
    width: "standard+wide",
    budget: "120-170",
    tech: "Fresh Foam X, komfortné objemy",
    weight: "~280 g",
    terrainDetail: "cesta",
    image: "nb-1080v14.png"
  },
  {
    id: "nb-860v14",
    brand: "New Balance",
    model: "860 v14",
    segment: "daily-stability",
    surface: "road",
    gait: "support",
    runnerLevel: "intermediate",
    targetDistance: "10-42k",
    cushioning: "medium",
    dropCat: "high",
    width: "standard+wide",
    budget: "120-170",
    tech: "Fresh Foam X + medial post",
    weight: "~300 g",
    terrainDetail: "cesta",
    image: "nb-860v14.png"
  },

  // ROAD – RACING / PERFORMANCE
  {
    id: "nike-vaporfly-4",
    brand: "Nike",
    model: "Vaporfly 4",
    segment: "racing",
    surface: "road",
    gait: "neutral",
    runnerLevel: "racer",
    targetDistance: "10-42k",
    cushioning: "high",
    dropCat: "mid",
    width: "standard",
    budget: "170+",
    tech: "ZoomX pena, karbónová platňa",
    weight: "~200 g",
    terrainDetail: "cesta, maratón",
    image: "nike-vaporfly-4.png"
  },
  {
    id: "nike-alphafly-3",
    brand: "Nike",
    model: "Alphafly 3",
    segment: "racing",
    surface: "road",
    gait: "neutral",
    runnerLevel: "racer",
    targetDistance: "10-42k",
    cushioning: "high",
    dropCat: "mid",
    width: "standard",
    budget: "170+",
    tech: "ZoomX, Air pods, karbón",
    weight: "~210 g",
    terrainDetail: "cesta, maratón",
    image: "nike-alphafly-3.png"
  },
  {
    id: "adidas-adios-pro-4",
    brand: "Adidas",
    model: "Adios Pro 4",
    segment: "racing",
    surface: "road",
    gait: "neutral",
    runnerLevel: "racer",
    targetDistance: "10-42k",
    cushioning: "high",
    dropCat: "low",
    width: "standard",
    budget: "170+",
    tech: "Lightstrike Pro, EnergyRods, karbón",
    weight: "~220 g",
    terrainDetail: "cesta",
    image: "adidas-adios-pro-4.png"
  },

  // TRAIL
  {
    id: "hoka-speedgoat-6",
    brand: "Hoka",
    model: "Speedgoat 6",
    segment: "trail-universal",
    surface: "trail",
    gait: "neutral",
    runnerLevel: "intermediate",
    targetDistance: "10-80k",
    cushioning: "high",
    dropCat: "low",
    width: "standard",
    budget: "120-170",
    tech: "Vibram Megagrip, univerzálny trail",
    weight: "~280 g",
    terrainDetail: "trail – univerzál",
    image: "hoka-speedgoat-6.png"
  },
  {
    id: "saucony-peregrine-14",
    brand: "Saucony",
    model: "Peregrine 14",
    segment: "trail-universal",
    surface: "trail",
    gait: "neutral",
    runnerLevel: "intermediate",
    targetDistance: "10-50k",
    cushioning: "medium",
    dropCat: "low",
    width: "standard",
    budget: "120-170",
    tech: "PWRRUN pena, PWRTRAC grip",
    weight: "~285 g",
    terrainDetail: "trail – univerzál",
    image: "saucony-peregrine-14.png"
  },
  {
    id: "asics-trabuco-max-3",
    brand: "ASICS",
    model: "Trabuco Max 3",
    segment: "trail-ultra",
    surface: "trail",
    gait: "neutral",
    runnerLevel: "intermediate",
    targetDistance: "30-100k",
    cushioning: "high",
    dropCat: "low",
    width: "standard",
    budget: "120-170",
    tech: "FF Blast, ASICSGRIP",
    weight: "~295 g",
    terrainDetail: "trail – ultra",
    image: "asics-trabuco-max-3.png"
  },
  {
    id: "altra-lone-peak-9",
    brand: "Altra",
    model: "Lone Peak 9",
    segment: "trail-universal",
    surface: "trail",
    gait: "neutral",
    runnerLevel: "intermediate",
    targetDistance: "10-80k",
    cushioning: "medium",
    dropCat: "zero",
    width: "wide-toebox",
    budget: "120-170",
    tech: "Zero drop, široká špička",
    weight: "~285 g",
    terrainDetail: "trail – univerzál",
    image: "altra-lone-peak-9.png"
  },
  {
    id: "topo-ultraventure-4",
    brand: "Topo",
    model: "Ultraventure 4",
    segment: "trail-ultra",
    surface: "trail",
    gait: "neutral",
    runnerLevel: "intermediate",
    targetDistance: "30-100k",
    cushioning: "high",
    dropCat: "low",
    width: "wide-toebox",
    budget: "120-170",
    tech: "ZipFoam, Vibram Megagrip",
    weight: "~295 g",
    terrainDetail: "trail – ultra",
    image: "topo-ultraventure-4.png"
  }
];
